export enum Piece {
    WHITE_PAWN = "WHITE_PAWN",
    WHITE_KNIGHT = "WHITE_KNIGHT",
    WHITE_BISHOP = "WHITE_BISHOP",
    WHITE_ROOK = "WHITE_ROOK",
    WHITE_QUEEN = "WHITE_QUEEN",
    WHITE_KING = "WHITE_KING",
    BLACK_PAWN = "BLACK_PAWN",
    BLACK_KNIGHT = "BLACK_KNIGHT",
    BLACK_BISHOP = "BLACK_BISHOP",
    BLACK_ROOK = "BLACK_ROOK",
    BLACK_QUEEN = "BLACK_QUEEN",
    BLACK_KING = "BLACK_KING"
}